#!/bin/bash
APP_NAME=$(basename "$PWD")
echo $APP_NAME

# Check for the config file and run script, check that the run script is
# executable, check that the config file is valid JSON and display a message.
